version: '2'
services:
  web:
    build: .
    ports:
     - "5000:4000"
    volumes:
     - .:/usr/src
    environment:
     - NODE_PORT=4000
     - DEBUG=my-namespace
     - URL=https://jeremiahgibson.io/
